{
 "title": "Appdex Score",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Meter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Mean Meter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate.mean\") AS \"mean_rate.mean\" FROM \"monitoring\".\"autogen\".\"application__sample_meter\" WHERE $timeFilter GROUP BY time(5124ms) FILL(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "15 Minute rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate15m\") AS \"15m_rate\" FROM \"monitoring\".\"autogen\".\"application__sample_meter\" WHERE $timeFilter GROUP BY time(5124ms) FILL(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Meter count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count.meter\") AS \"mean_rate.meter\" FROM \"monitoring\".\"autogen\".\"application__sample_meter\" WHERE $timeFilter GROUP BY time(5124ms) FILL(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"mean_value\" FROM \"monitoring\".\"autogen\".\"application.httprequests__active\" WHERE time > now() - 1h GROUP BY time(5142ms) FILL(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Appdex Score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Fraustating",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "query": "SELECT mean(\"frustrating\") AS \"mean_frustrating\", mean(\"samples\") AS \"mean_samples\", mean(\"satisfied\") AS \"mean_satisfied\", mean(\"tolerating\") AS \"mean_tolerating\" FROM \"monitoring\".\"autogen\".\"application.httprequests__apdex\" WHERE time > :dashboardTime: GROUP BY time($interval) FILL(null)",
     "select": [
      [
       { "params": [ "frustrating" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "satisfied",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "satisfied" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tolorating",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "tolerating" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Samples",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "samples" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}