version: "3"
services:
  influxdb:
    container_name: influx_db
    image: influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=cyberhck
      - INFLUXDB_ADMIN_PASSWORD=secret
      - INFLUXDB_DB=monitoring
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003

  chronograf:
    container_name: chronograf
    image: chronograf
    environment:
      - influxdb-url=influxdb:8086
    ports:
      - 8888:8888

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - 3000:3000